services:
  - type: web
    name: discord-bot
    runtime: node
    buildCommand: npm install
    startCommand: node src/index.js
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: NOWPAYMENTS_API_KEY
        sync: false
      - key: NOWPAYMENTS_IPN_SECRET
        sync: false