services:
  - type: web
    name: discord-bot-mvp
    runtime: node
    buildCommand: |
      cd src/dashboard
      npm install
      npm run build
      cd ../..
      npm install
    startCommand: node server/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GUILD_ID
        value: 1335686213931237437
      - key: PORT
        value: 3000
    plan: free
    staticPublishPath: "dashboard/build"