services:
  - type: web
    name: discord-bot-dashboard
    runtime: node
    buildCommand: |
      cd dashboard && npm install && npm run build
      cd .. && npm install
    startCommand: node server/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        value: https://your-app.onrender.com/auth/callback
    staticPublishPath: dashboard/dist # Vite builds to 'dist' by default